In [1]:
import pandas as pd
import numpy as np

In [2]:
flats=pd.read_csv('C:/Users/8429s/OneDrive/Desktop/Placement/Projects/Real Estate Price Prediction and Recommendation System/Data_Clean/flats_Clean.csv')
house=pd.read_csv('C:/Users/8429s/OneDrive/Desktop/Placement/Projects/Real Estate Price Prediction and Recommendation System/Data_Clean/independent-house_clean.csv')

In [3]:
flats.sample()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
1102,3 BHK Flat in Nirvana Country,flat,the close north,2.35,11767.0,1997.0,Super Built up area 1997(185.53 sq.m.)Built Up...,3,3,3+,not available,"8/9, Nirvana Country, Gurgaon, Haryana",8.0,North-East,5 to 10 Year Old,"['Sector 55-56 Metro Station', 'Eros City Squa...","Situated in nirvana country, gurgaon, the clos...","['5 Fan', '1 Exhaust Fan', '3 Geyser', '1 Stov...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction4 out of..."

In [4]:
house.sample()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
820,3 Bedroom House for sale in Sushant Lok Phase 1,house,sushant lok 1 builder floors,13.0,48148.0,2700.0,Plot area 300(250.84 sq.m.),3,3,3+,pooja room,"Sushant Lok Phase 1, Gurgaon, Haryana",4.0,North,0 to 1 Year Old,"['Huda city centre metro station', 'New Life C...",Sushant lok a block gated line . Floor wise bu...,"['8 Wardrobe', '12 Fan', '4 Geyser', '12 AC', ...",['Visitor Parking'],"['Environment5 out of 5', 'Safety4.5 out of 5'..."

In [5]:
df=pd.concat([flats,house],ignore_index=True)

In [6]:
df.shape

(3960, 20)

In [7]:
df=df.sample(df.shape[0],ignore_index=True)

In [8]:
df.sample(5)

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
614,18 Bedroom House for sale in Suncity,house,independent,5.50,38194.0,1440.0,Plot area 160(133.78 sq.m.),18,18,3+,servant room,"11111, Suncity, Gurgaon, Haryana",4.0,South-West,1 to 5 Year Old,"['Sector 54 chowk metro station', 'Sector metr...",18 bed room newly built up in 160 yds plot is ...,"['1 Water Purifier', '22 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'High Ceiling...","['Environment5 out of 5', 'Safety5 out of 5', ..."
1217,3 BHK Flat in Sector 63A Gurgaon,flat,birla navya,3.30,15348.0,2150.0,Super Built up area 2150(199.74 sq.m.)Carpet a...,3,3,3,servant room,"H-42, 4th Floor, Amoda, Sector 63A Gurgaon, Gu...",4.0,West,Dec 2023,"['Sector 54 Chowk Metro Station', 'WorldMark G...",This is a premium 3 bhk+utility+terrace proper...,"['6 Fan', '8 Light', 'No AC', 'No Bed', 'No Ch...","['Feng Shui / Vaastu Compliant', 'Intercom Fac...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
1985,3 BHK Flat in Sector 102 Gurgaon,flat,shapoorji pallonji joyville gurugram,2.00,17729.0,1128.0,Super Built up area 1852(172.06 sq.m.)Built Up...,3,3,3+,store room,"303, Sector 102 Gurgaon, Gurgaon, Haryana",1.0,South,1 to 5 Year Old,"['Khan Market', 'The Esplanade Mall', 'Dwarka ...",Check out this 3 bhk apartment for sale in sha...,NaN,"['Water purifier', 'Security / Fire Alarm', 'F...","['Green Area4 out of 5', 'Construction5 out of..."
3758,4 Bedroom House for sale in Sector 46 Gurgaon,house,independent,2.25,24510.0,918.0,Plot area 102(85.28 sq.m.)Built Up area: 90 sq...,4,3,3,study room,"204, Sector 46 Gurgaon, Gurgaon, Haryana",3.0,North-East,1 to 5 Year Old,"['Axis bank ATM', 'State bank of india ATM', '...","This house is a good loction near park , schoo...","['3 Fan', '1 Exhaust Fan', '2 Geyser', '5 Ligh...","['Feng Shui / Vaastu Compliant', 'False Ceilin...","['Environment4 out of 5', 'Safety4 out of 5', ..."
375,4 BHK Flat in Sector 108 Gurgaon,flat,sobha city,4.10,23401.0,1752.0,Super Built up area 2344(217.76 sq.m.)Built Up...,4,5,3,"study room,servant room","C1 Tower, Sector 108 Gurgaon, Gurgaon, Haryana",25.0,North-East,0 to 1 Year Old,"['Dwarka Sector 21', 'Dwarka Expressway', 'Vas...",This is your chance to own a 4 bhk residential...,"['1 Water Purifier', '4 Fan', '1 Dining Table'...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment4 out of 5', 'Lifestyle4.5 out of..."

In [9]:
df.to_csv('C:/Users/8429s/OneDrive/Desktop/Placement/Projects/Real Estate Price Prediction and Recommendation System/Data_Clean/flats_and_house.csv',index=False)