In [4]:
import pandas as pd
import numpy as np

In [5]:
flats=pd.read_csv('C:/Users/8429s/OneDrive/Desktop/Placement/Projects/Real Estate Price Prediction and Recommendation System/Data_Clean/flats_Clean.csv')
house=pd.read_csv('C:/Users/8429s/OneDrive/Desktop/Placement/Projects/Real Estate Price Prediction and Recommendation System/Data_Clean/independent-house_clean.csv')

In [6]:
flats.sample()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
1067,4 BHK Flat in Sector 65 Gurgaon,flat,emaar mgf emerald floors premier,2.8,16969.0,1650.0,Super Built up area 1975(183.48 sq.m.)Built Up...,4,4,3,study room,"101, Sector 65 Gurgaon, Gurgaon, Haryana",2.0,North,1 to 5 Year Old,"['WorldMark Gurgaon', 'Sohna Road', 'Golf Cour...",This lovely 4 bhk apartment/flat in sector 65 ...,"['4 Wardrobe', '6 Fan', '1 Exhaust Fan', '5 Ge...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area4.5 out of 5', 'Construction5 out ..."

In [7]:
house.sample()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
139,6 Bedroom House for sale in Madanpuri,house,independent,0.9,10000.0,900.0,Plot area 100(83.61 sq.m.),6,4,3,"servant room,others","Madanpuri, Gurgaon, Haryana",3.0,North-East,10+ Year Old,"['Dev Man Kathuria Clinic', 'Dr. Madan Clinic'...","Corner property, two side open, 30 by 30 with ...","['5 Fan', '1 Exhaust Fan', '1 Geyser', '6 Ligh...","['Feng Shui / Vaastu Compliant', 'Water Storag...","['Environment4 out of 5', 'Lifestyle4 out of 5..."

In [8]:
df=pd.concat([flats,house],ignore_index=True)

In [9]:
df.shape

(3960, 20)

In [10]:
df=df.sample(df.shape[0],ignore_index=True)

In [11]:
df.sample(5)

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
1314,3 BHK Flat in Sector 77 Gurgaon,flat,emaar mgf palm hills,1.90,9500.0,2000.0,Super Built up area 2000(185.81 sq.m.)Carpet a...,3,4,3+,servant room,"Sector 77 Gurgaon, Gurgaon, Haryana",6.0,South-West,0 to 1 Year Old,"['Sapphire 83 Mall', 'Dwarka Expressway', 'Soh...","Ready to move in property with wardrobes, fans...","['4 Wardrobe', '7 Fan', '1 Exhaust Fan', '4 Ge...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area4 out of 5', 'Construction4.5 out ..."
589,3 BHK Flat in Sector 103 Gurgaon,flat,indiabulls centrum park,1.34,7882.0,1700.0,Super Built up area 1725(160.26 sq.m.)Carpet a...,3,3,3+,"pooja room,study room,servant room,store room","154562, Sector 103 Gurgaon, Gurgaon, Haryana",12.0,East,1 to 5 Year Old,"['Gurgaon Dreamz Mall', 'HUDA Market, Sector 1...",This lovely 3 bhk apartment/flat in sector 103...,"['9 Fan', '9 Light', '4 AC', '1 Modular Kitche...","['Lift(s)', 'Swimming Pool', 'Park', 'Shopping...","['Green Area5 out of 5', 'Construction4 out of..."
2307,3 BHK Flat in Sector 67 Gurgaon,flat,m3m merlin,2.65,12945.0,2047.0,Super Built up area 2047(190.17 sq.m.)Built Up...,3,3,3,others,"101, Sector 67 Gurgaon, Gurgaon, Haryana",NaN,North-East,1 to 5 Year Old,"['Airia Mall', 'Golf Course Extension Road', '...",This lovely 3 bhk apartment/flat in sector 67 ...,"['6 Fan', '1 Exhaust Fan', '4 Geyser', '1 Stov...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area4 out of 5', 'Construction4 out of..."
2681,3 BHK Flat in Sector 107 Gurgaon,flat,m3m woodshire,1.30,8922.0,1457.0,Super Built up area 1943(180.51 sq.m.)Built Up...,3,3,3+,pooja room,"Dwarka Expressway, Sector 107 Gurgaon, Gurgaon...",4.0,West,1 to 5 Year Old,"['Signum 107', 'Nora Solomon Medicenter', 'Ind...",Available 3 bhk spacious apartment at best pri...,"['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '1 Ge...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area4.5 out of 5', 'Construction5 out ..."
3410,3 BHK Flat in Sector 37C Gurgaon,flat,corona optus,1.25,7090.0,1763.0,Super Built up area 1763(163.79 sq.m.)Built Up...,3,3,3,others,"T1-101, Sector 37C Gurgaon, Gurgaon, Haryana",4.0,North-West,1 to 5 Year Old,"['The Esplanade Mall', 'Gurugram Road', 'Delhi...",Optus corona is a ready to move residential pr...,NaN,"['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area5 out of 5', 'Construction4 out of..."

In [12]:
df.to_csv('C:/Users/8429s/OneDrive/Desktop/Placement/Projects/Real Estate Price Prediction and Recommendation System/Data_Clean/flats_and_house.csv')